# Aerospace Config

#==================#
# Startup Commands #
#==================#
# Pre-startup:
after-login-command = []

# Post-startup:
after-startup-command = []

# Start AeroSpace at login
start-at-login = true # Note: This MUST be enabled for the pre and post startup commands to work at all

# Note: Available commands you can use during startup are here: https://nikitabobko.github.io/AeroSpace/commands


#===================#
# Windows           #
#===================#
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
# Note: For more information, see https://nikitabobko.github.io/AeroSpace/guide#normalization

# Set how much of windows are visible in "accordion" mode:
accordion-padding = 10

# Set default root container layout:
default-root-container-layout = 'tiles' # Possible values are 'tiles' or 'accordion'


# Set default container orientation:
default-root-container-orientation = 'auto' # Possible values: horizontal|vertical|auto

# Mouse follows focus when focused monitor changes:
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = 'move-mouse window-lazy-center'

# Turn off the useless "hide apps" feature of macOS:
automatically-unhide-macos-hidden-apps = true

# Set key mapping:
key-mapping.preset = 'qwerty' # Possible values: (qwerty|dvorak)

# Set gaps between windows:
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

# 'main' binding mode declaration:
[mode.main.binding]

#===================#
# Shortcuts         #
#===================#
# Switch layout:
ctrl-alt-v = 'layout tiles horizontal vertical'
ctrl-alt-h = 'layout accordion horizontal vertical'

# toggle window zoom:
cmd-alt-f = 'fullscreen'

# toggle 'macOS' full screen:
cmd-shift-f = 'macos-native-fullscreen'

# Change focused window (vim version):
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move current window to another pane (vim version):
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Resize windows:
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# Change positions of the currently focused tile (vim version):
cmd-alt-h = ['join-with left', 'mode main']
cmd-alt-j = ['join-with down', 'mode main']
cmd-alt-k = ['join-with up', 'mode main']
cmd-alt-l = ['join-with right', 'mode main']

# Switch to a particular workspace:
alt-b = 'workspace Browsing(b)'
alt-s = 'workspace Social(s)'
alt-c = 'workspace Coding(c)'
alt-u = 'workspace Uni(u)'
alt-p = 'workspace Productivity(p)'
alt-e = 'workspace Extra(e)'
alt-1 = 'workspace Project-1'
alt-2 = 'workspace Project-2'
alt-o = 'workspace Others(o)'
alt-t = 'workspace Task_Management(t)'

# Move the app that currently has focus to another workspace:
alt-shift-b = 'move-node-to-workspace Browsing(b)'
alt-shift-s = 'move-node-to-workspace Social(s)'
alt-shift-u = 'move-node-to-workspace Uni(u)'
alt-shift-p = 'move-node-to-workspace Productivity(p)'
alt-shift-c = 'move-node-to-workspace Coding(c)'
alt-shift-1 = 'move-node-to-workspace Project-1'
alt-shift-2 = 'move-node-to-workspace Project-2'
alt-shift-t = 'move-node-to-workspace Task_Management(t)'
alt-shift-e = 'move-node-to-workspace Extra(e)'
alt-shift-o = 'move-node-to-workspace Others(o)'

# Switch back and forth between the current and previous workspace:
alt-tab = 'workspace-back-and-forth'

# Move workspace to another display:
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'

# Service bindings:
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2


# Set float layout for Extra workspace
[[on-window-detected]]
if.workspace = 'Extra(e)'
run = 'layout floating'
check-further-callbacks = true

#===================================================#
# Workspace Assignments for individual Applications #
#===================================================#

# Calendar
[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = ['layout tiling', 'move-node-to-workspace Productivity(p)']
check-further-callbacks = true

# # Finder
# [[on-window-detected]]
# if.app-id = 'com.apple.finder'
# run = ['layout tiling', 'move-node-to-workspace Productivity(p)']

# Discord
[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = ['layout tiling', 'move-node-to-workspace Social(s)']

# WhatsApp
[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = ['layout tiling', 'move-node-to-workspace Social(s)']

# Todoist
[[on-window-detected]]
if.app-id = 'com.todoist.mac.Todoist'
run = ['layout tiling', 'move-node-to-workspace Task_Management(t)']

# Ghostty
[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = ['layout tiling', 'move-node-to-workspace Coding(c)']

# Spotify
[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['layout tiling', 'move-node-to-workspace Others(o)']

# Arc
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = ['layout tiling', 'move-node-to-workspace Browsing(b)']

# Spark Mail
[[on-window-detected]]
if.app-id = 'com.readdle.SparkDesktop'
run = ['layout tiling', 'move-node-to-workspace Productivity(p)']

# Slack
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['layout tiling', 'move-node-to-workspace Productivity(p)']

[[on-window-detected]]
if.app-id = 'com.apple.QuickLookFramework'
run = ['layout floating']

#======================#
# Misc. Info and Notes #
#======================#
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands
